# Generated by Django 5.1.1 on 2024-10-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogImages/'),
        ),
    ]
